In [1]:
import pandas as pd
import mysql.connector

# Cargar los datos del archivo Excel ya limpio
df = pd.read_excel('INPUT/ING AGOSTO.xlsx', skiprows=7)
# Eliminar la columna 'NÂº'
df = df.drop('NÂº', axis=1)

# Seleccionar las columnas relevantes del DataFrame original
selected_columns = [
    'CÃ³digo Ingreso', 'Fecha Ingreso', 'Motivo de Ingreso', 'Gerencia Solicitante', 
    'Departamento Solicitante', 'Ubicacion', 'Partida Presupuestaria', 
    'Proveedor', 'CÃ³digo Item', 'Item', 'Unidad Medida', 
    'Grupo', 'Subgrupo', 'Cantidad', 'Precio Unitario', 'Importe Calculado'
]

# Crear un nuevo DataFrame con las columnas seleccionadas
df_selected = df[selected_columns]

# Definir los nuevos nombres en el orden deseado
new_column_names = [
    'codigo_ingreso', 'fecha_ingreso', 'motivo_ingreso', 
    'gerencia_solicitante', 'departamento_solicitante', 
    'ubicacion', 'partida_presupuestaria', 'proveedor', 
    'codigo_item', 'descripcion', 'unidad_medida', 
    'grupo', 'sub_grupo', 'cantidad', 
    'precio_unitario', 'importe_calculado'
]

# Cambiar los nombres de las columnas
df_selected.columns = new_column_names

# Configurar la conexiÃ³n a la base de datos MySQL
connection = mysql.connector.connect(
    host='192.168.100.50',        # Cambia por tu host
    user='mantto',                # Cambia por tu usuario
    password='Sistemas0,',        # Cambia por tu contraseÃ±a
    database='Catalogo'           # Cambia por tu base de datos
)

cursor = connection.cursor()

# Insertar los datos en la tabla `ingreso_test`
insert_query = """
INSERT INTO ingreso_test (codigo_ingreso, fecha_ingreso, motivo_ingreso, 
                          gerencia_solicitante, departamento_solicitante, 
                          ubicacion, partida_presupuestaria, proveedor, 
                          codigo_item, descripcion, unidad_medida, 
                          grupo, sub_grupo, cantidad, 
                          precio_unitario, importe_calculado) 
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

# Iterar sobre las filas del dataframe e insertar cada una en la base de datos
for index, row in df_selected.iterrows():
    cursor.execute(insert_query, (
        row['codigo_ingreso'], row['fecha_ingreso'], row['motivo_ingreso'], 
        row['gerencia_solicitante'], row['departamento_solicitante'], 
        row['ubicacion'], row['partida_presupuestaria'], row['proveedor'], 
        row['codigo_item'], row['descripcion'], row['unidad_medida'], 
        row['grupo'], row['sub_grupo'], row['cantidad'], 
        row['precio_unitario'], row['importe_calculado']
    ))

# Confirmar la transacciÃ³n
connection.commit()

# Cerrar la conexiÃ³n
cursor.close()
connection.close()

print("Datos insertados exitosamente.")

DatabaseError: 1364 (HY000): Field 'id' doesn't have a default value